### ISSUE TITLE
リストのマージン変更

### ISSUE THREAD

**Issue by satorika** [doghouse-studio/github-lessonsite#7]
```html
<ul class="list-l">
  <li>リスト1</li>
  <li>リスト2</li>
</ul>
```
上記のマークアップのcssが

```css
.list-l {
  padding: 0 2px;
  width: 320px;
}

.list-l li {
  margin: 2px 3px;
  height: 25px;
}
```

となっているので、`li`の`margin-bottom`と`margin-top`を**4px**にしてください。
